- hosts: all
  become: yes
  tasks:
    - name: Install Dependencies
      apt:
       name: "{{ packages }}"
      vars:
       packages:
         - build-essential
         - tcl

    - name: Download Redis
      get_url:
        url: http://download.redis.io/redis-stable.tar.gz
        dest: /tmp/redis-stable.tar.gz

    - name: Extract Redis-server sources from archive
      unarchive:
        src: /tmp/redis-stable.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Build Sources
      make:
        chdir: /tmp/redis-stable
        target: install
      become: yes

    - name: Create redis group
      group:
        name: redis
        state: present

    - name: create redis user
      user:
        name: redis
        group: redis
        createhome: no
        append: yes

    - name: Make directories
      file:
        path: "{{item.path}}"
        state: "{{item.state}}"
        owner: redis
        group: redis
        mode: 0770
      with_items:
        - {path: "/etc/redis/", state: "directory"}
        - {path: "/var/lib/redis/", state: "directory"}
        - {path: "/var/lib/redis/6379/", state: "directory"}
        - {path: "/var/lib/redis/6380/", state: "directory"}
        - {path: "/var/log/redis/", state: "directory"}

    - name: Create Service and Configs
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
      with_items:
      - { src: redis.j2, dest:  /etc/systemd/system/redis@.service}
      - { src: 6379.j2, dest: /etc/redis/6379.conf}
      - { src: 6380.j2, dest: /etc/redis/6380.conf}

    - name: Start Services
      service:
        name: "{{item}}"
        enabled: yes
        state: started
      with_items:
      - redis@6379
      - redis@6380
